-- SCHEMA operacaopipa
CREATE DATABASE `operacaopipa` /*!40100 DEFAULT CHARACTER SET utf8 */;

-- TABELA PONTOCOLETA
CREATE TABLE `pontocoleta` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PONTOCOLETA` varchar(60) NOT NULL,
  `GEOLOCALIZACAO` varchar(50) DEFAULT NULL,
  `STATUS` varchar(7) DEFAULT NULL,
  `CODGCDA` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=6 DEFAULT CHARSET=utf8;


-- TABELA CIDADE
CREATE TABLE `cidade` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(60) NOT NULL,
  `UF` char(2) NOT NULL,
  `CODPONTOCOLETA` int(11) NOT NULL,
  `GEOLOCALIZACAO` varchar(50) DEFAULT NULL,
  `NRHABITANTES` int(11) DEFAULT NULL,
  `EMAIL` varchar(60) DEFAULT NULL,
  `CARRMAX` int(11) NOT NULL,
  `COORDSOPMUNICIPAL` varchar(60) DEFAULT NULL,
  `FONESOPMUNICIPAL` varchar(16) DEFAULT NULL,
  `NUMPIPEIROS` int(11) DEFAULT NULL,
  `STATUS` varchar(7) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CIDADE_PONTOCOLETA` (`CODPONTOCOLETA`),
  CONSTRAINT `FK_CIDADE_PONTOCOLETA` FOREIGN KEY (`CODPONTOCOLETA`) REFERENCES `pontocoleta` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=23 DEFAULT CHARSET=utf8;


-- TABELA MILITAR
CREATE TABLE `militar` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `POSTOGRAD` varchar(10) NOT NULL,
  `CPF` varchar(14) NOT NULL,
  `BANCO` varchar(50) DEFAULT NULL,
  `NUMBANCO` varchar(20) NOT NULL,
  `AGENCIA` varchar(20) NOT NULL,
  `CONTA` varchar(30) NOT NULL,
  `TELEFONE` varchar(16) DEFAULT NULL,
  `CELULAR` varchar(16) DEFAULT NULL,
  `EMAIL` varchar(70) DEFAULT NULL,
  `STATUS` varchar(7) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;


-- TABELA USUARIO
CREATE TABLE `usuario` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `USUARIO` varchar(60) NOT NULL,
  `SENHA` varchar(60) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=2 DEFAULT CHARSET=utf8;


-- TABELA INDICE
CREATE TABLE `indice` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DSC_INDICE` varchar(100) NOT NULL,
  `INDICE` float DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=5 DEFAULT CHARSET=utf8;


-- TABELA VEICULO
CREATE TABLE `veiculo` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `PLACA` varchar(10) NOT NULL,
  `RENAVAM` varchar(20) DEFAULT NULL,
  `CAPACIDADEPIPA` float NOT NULL,
  `MARCAMODELO` varchar(50) DEFAULT NULL,
  `STATUS` varchar(7) DEFAULT NULL,
  PRIMARY KEY (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;


-- TABELA PIPEIRO
CREATE TABLE `pipeiro` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `NOME` varchar(100) NOT NULL,
  `CODCIDADE` int(11) NOT NULL,
  `CNH` int(11) DEFAULT NULL,
  `VALIDADECNH` date DEFAULT NULL,
  `IDENTIDADE` int(11) NOT NULL,
  `ORGAOEMISSORUF` varchar(15) NOT NULL,
  `NIT` int(11) NOT NULL,
  `CPF` int(11) NOT NULL,
  `CODBANCO` varchar(10) NOT NULL,
  `BANCO` varchar(30) DEFAULT NULL,
  `AGENCIA` varchar(15) NOT NULL,
  `CONTA` varchar(15) NOT NULL,
  `CODVEICULO` int(11) NOT NULL,
  `SALDOSIAF` float DEFAULT NULL,
  `RECURSOANO` float DEFAULT NULL,
  `RESTOPAGAR` float DEFAULT NULL,
  `STATUS` varchar(7) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PIPEIRO_CIDADE` (`CODCIDADE`),
  KEY `FK_PIPEIRO_VEICULO` (`CODVEICULO`),
  CONSTRAINT `FK_PIPEIRO_CIDADE` FOREIGN KEY (`CODCIDADE`) REFERENCES `cidade` (`ID`),
  CONSTRAINT `FK_PIPEIRO_VEICULO` FOREIGN KEY (`CODVEICULO`) REFERENCES `veiculo` (`ID`)
) ENGINE=InnoDB AUTO_INCREMENT=9 DEFAULT CHARSET=utf8;

-- TABELA PONTOABASTECIMENTO
CREATE TABLE `pontoabastecimento` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COMUNIDADE` varchar(60) NOT NULL,
  `POPULACAO` int(11) NOT NULL,
  `DISTANCIA` float NOT NULL,
  `CODCIDADE` int(11) NOT NULL,
  `GEOREFERENCIAMENTO` varchar(50) DEFAULT NULL,
  `VOLUME` float DEFAULT NULL,
  `ASFALTO` float NOT NULL,
  `TERRA` float NOT NULL,
  `APONTADOR` varchar(60) NOT NULL,
  `SUBSTITUTO` varchar(60) DEFAULT NULL,
  `STATUS` varchar(7) DEFAULT NULL,
  `CODGCDA` int(11) DEFAULT NULL,
  `POPULACAO_5L` int(11) DEFAULT NULL,
  `POPULACAO_DEFAULT` int(11) DEFAULT NULL,
  `LITROS_DIARIO` int(11) DEFAULT NULL,
  `COD_INDICE` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_PONTOABASTECIMENTO_CIDADE` (`CODCIDADE`),
  KEY `FK_PONTOABASTECIMENTO_INDICE_idx` (`COD_INDICE`),
  CONSTRAINT `FK_PONTOABASTECIMENTO_CIDADE` FOREIGN KEY (`CODCIDADE`) REFERENCES `cidade` (`ID`),
  CONSTRAINT `FK_PONTOABASTECIMENTO_INDICE` FOREIGN KEY (`COD_INDICE`) REFERENCES `indice` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=69 DEFAULT CHARSET=utf8;


-- TABELA AFASTAMENTO
CREATE TABLE AFASTAMENTO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	D1IDA VARCHAR(14)NOT NULL,
	D1VOLTA VARCHAR(14),
	D2IDA VARCHAR(14),
	D2VOLTA VARCHAR(14),
	D3IDA VARCHAR(14),
	D3VOLTA VARCHAR(14),
	D4IDA VARCHAR(14),
	D4VOLTA VARCHAR(14),
	D5IDA VARCHAR(14),
	D5VOLTA VARCHAR(14),
	D6DA VARCHAR(14),
	D6VOLTA VARCHAR(14),
	D7IDA VARCHAR(14),
	D7VOLTA VARCHAR(14)
);

-- TABELA ADITAMENTO
CREATE TABLE ADITAMENTO (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	ADITAMENTO VARCHAR(100) NOT NULL
);

-- TABELA PROPOSTA
CREATE TABLE PROPOSTA (
	ID INT NOT NULL PRIMARY KEY AUTO_INCREMENT,
	NUMERO INT NOT NULL,
	CODMILITAR INT NOT NULL,
	CODADITAMENTO INT NOT NULL,
	CODAFASTAMENTO INT,
	EVENTOINICIO VARCHAR(14),
	EVENTOFIM VARCHAR(14),
	EVENTODESC VARCHAR(150),
	CIDADES VARCHAR(150),
	ALOJAMENTO INT,
	VEICULO INT,
	VALORTOTAL FLOAT,
	DATA DATE,
	REQUISITANTE VARCHAR(150),
	ORDENADORDESPESA VARCHAR(150),
	CONSTRAINT FK_PROPOSTA_MILITAR FOREIGN KEY (CODMILITAR)REFERENCES MILITAR (ID),
	CONSTRAINT FK_PROPOSTA_ADITAMENTO FOREIGN KEY (CODADITAMENTO) REFERENCES ADITAMENTO (ID),
	CONSTRAINT FK_PROPOSTA_AFASTAMENTO FOREIGN KEY (CODAFASTAMENTO)REFERENCES AFASTAMENTO (ID)
);

-- TABELA ASSINATURAS
CREATE TABLE `assinaturas` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `funcionalidade` int(11) NOT NULL,
  `cargo` varchar(500) NOT NULL,
  `nome` varchar(500) NOT NULL,
  `abrev` varchar(45) NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_ASSI_FUNC_idx` (`funcionalidade`),
  CONSTRAINT `FK_ASSI_FUNC` FOREIGN KEY (`funcionalidade`) REFERENCES `funcionalidades` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=3 DEFAULT CHARSET=utf8;

-- TABELA FUNCIONALIDADES
CREATE TABLE `funcionalidades` (
  `id` int(11) NOT NULL,
  `nome` varchar(500) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- TABELA HISTORICO DISTRISB.
CREATE TABLE `hitorico_distribuicao` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `DATA_INTERACAO` date NOT NULL,
  `COD_USUARIO` int(11) NOT NULL,
  `OBSERVACAO` varchar(100) DEFAULT NULL,
  `NUM_BAR` int(11) DEFAULT NULL,
  `DATA_SORTEIO` date DEFAULT NULL,
  `DATA_BAR` date DEFAULT NULL,
  `MES` int(11) DEFAULT NULL,
  `ANO` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_COD_USUARIO_idx` (`COD_USUARIO`),
  CONSTRAINT `FK_COD_USUARIO` FOREIGN KEY (`COD_USUARIO`) REFERENCES `usuario` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=55 DEFAULT CHARSET=utf8;

-- TABELA DE DIAS DISTRIB.
CREATE TABLE `interacao_datas` (
  `data` date NOT NULL,
  `data_extenso` varchar(50) NOT NULL,
  `indice` int(11) NOT NULL,
  `dias` int(11) DEFAULT NULL,
  `eh_fim_de_semana` int(11) NOT NULL,
  `exibir_coluna` int(11) NOT NULL,
  `cod_historico_distribuicao` int(11) NOT NULL,
  `mes` int(11) NOT NULL,
  `ano` int(11) NOT NULL,
  `cod_pa` int(11) NOT NULL,
  `cod_pipeiro` int(11) NOT NULL,
  KEY `FK_DATAS_HISTORICO_idx` (`cod_historico_distribuicao`),
  KEY `FK_DATAS_PONTO_idx` (`cod_pa`),
  KEY `FK_DATAS_CIDADE_idx` (`cod_pipeiro`),
  CONSTRAINT `FK_DATAS_INT_HISTORICO` FOREIGN KEY (`cod_historico_distribuicao`) REFERENCES `hitorico_distribuicao` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_DATAS_INT_PA` FOREIGN KEY (`cod_pa`) REFERENCES `pontoabastecimento` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_DATAS_INT_PIPEIRO` FOREIGN KEY (`cod_pipeiro`) REFERENCES `pipeiro` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB DEFAULT CHARSET=utf8;

-- TABELA DE DISTRIB.
CREATE TABLE `interacao_ditribuicao` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COD_CIDADE` int(11) NOT NULL,
  `COD_PIPEIRO` int(11) NOT NULL,
  `COD_VEICULO` int(11) NOT NULL,
  `COD_PC` int(11) NOT NULL,
  `COD_HISTORICO_DISTRIBUICAO` int(11) NOT NULL,
  `QTD_DIAS` int(11) NOT NULL,
  `QTD_LITROS_PESSOA` int(11) NOT NULL,
  `VALOR_TOTAL` float NOT NULL,
  `KM_TOTAL` int(11) NOT NULL,
  `TOTAL_VIAGEM_FORMULA` float NOT NULL,
  `TOTAL_VIAGEM_REAL` int(11) NOT NULL,
  `TOTAL_APONTADORES` int(11) NOT NULL,
  `TOTAL_PESSOAS` int(11) NOT NULL,
  `TOTAL_QTD_AGUA` float NOT NULL,
  `TOTAL_DISTANCIA` int(11) NOT NULL,
  `MES` int(11) NOT NULL,
  `ANO` int(11) NOT NULL,
  `NUM_LACRE` int(11) DEFAULT NULL,
  `NUM_OS` int(11) DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_CIDADE_idx` (`COD_CIDADE`),
  KEY `FK_COD_PIPEIRO_idx` (`COD_PIPEIRO`),
  KEY `FK_COD_VEICULO_idx` (`COD_VEICULO`),
  KEY `FK_COD_PC_idx` (`COD_PC`),
  KEY `FK_COD_HIST_DIST_idx` (`COD_HISTORICO_DISTRIBUICAO`),
  CONSTRAINT `FK_COD_CIDADE` FOREIGN KEY (`COD_CIDADE`) REFERENCES `cidade` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_HIST_DIST` FOREIGN KEY (`COD_HISTORICO_DISTRIBUICAO`) REFERENCES `hitorico_distribuicao` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_PC` FOREIGN KEY (`COD_PC`) REFERENCES `pontocoleta` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_PIPEIRO` FOREIGN KEY (`COD_PIPEIRO`) REFERENCES `pipeiro` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_VEICULO` FOREIGN KEY (`COD_VEICULO`) REFERENCES `veiculo` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=119 DEFAULT CHARSET=utf8;

-- TABELA DE DISTRIB.
CREATE TABLE `interacao_pipeiro_pa` (
  `ID` int(11) NOT NULL AUTO_INCREMENT,
  `COD_PIPEIRO` int(11) NOT NULL,
  `COD_PA` int(11) NOT NULL,
  `TOTAL_QTD_AGUA` float NOT NULL,
  `VIAGEM_FORMULA` float NOT NULL,
  `VIAGEM_REAL` int(11) NOT NULL,
  `VALOR_BRUTO` float NOT NULL,
  `KM_PERCORRIDO` int(11) NOT NULL,
  `OBS` varchar(500) DEFAULT NULL,
  `COD_HISTORICO_DISTRIBUICAO` int(11) NOT NULL,
  `INDICE` float DEFAULT NULL,
  PRIMARY KEY (`ID`),
  KEY `FK_COD_PIPEIRO_1_idx` (`COD_PIPEIRO`),
  KEY `FK_COD_PA_idx` (`COD_PA`),
  KEY `FK_COD_HIST_DIST_1_idx` (`COD_HISTORICO_DISTRIBUICAO`),
  CONSTRAINT `FK_COD_HIST_DIST_1` FOREIGN KEY (`COD_HISTORICO_DISTRIBUICAO`) REFERENCES `hitorico_distribuicao` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_PA_1` FOREIGN KEY (`COD_PA`) REFERENCES `pontoabastecimento` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION,
  CONSTRAINT `FK_COD_PIPEIRO_1` FOREIGN KEY (`COD_PIPEIRO`) REFERENCES `pipeiro` (`ID`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=885 DEFAULT CHARSET=utf8;

-- TABELA DE INTERACAO USUARIO
CREATE TABLE `interacao_usuario` (
  `id` int(11) NOT NULL AUTO_INCREMENT,
  `funcionalidade` int(11) NOT NULL,
  `acao` varchar(45) NOT NULL,
  `obs` varchar(500) DEFAULT NULL,
  `data` date NOT NULL,
  PRIMARY KEY (`id`),
  KEY `FK_FUCIONALIDADE_idx` (`funcionalidade`),
  CONSTRAINT `FK_FUCIONALIDADE` FOREIGN KEY (`funcionalidade`) REFERENCES `funcionalidades` (`id`) ON DELETE NO ACTION ON UPDATE NO ACTION
) ENGINE=InnoDB AUTO_INCREMENT=31 DEFAULT CHARSET=utf8;